---
- name: Install Collectd
  apt: pkg=collectd={{ collectd_version }}
       install_recommends={{ collectd_install_recommends }}
       state=present
       force=yes

- name: Configure Collectd
  template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf
  notify:
    - Restart Collectd
